getHelp/urls.py
from django.urls import path

from getHelp.views import index

urlpatterns = [
	path('', index, name='getHelp'),
]

home/urls.py
from django.urls import path

from .views import index

urlpatterns = [
	path('', index, name='home'),
]

rotacalendar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

urlpatterns = [
	              path('admin/', admin.site.urls),
	              path('', include('home.urls')),  # Include the URLs from the 'home' app
	              path('signup/', include('signup.urls')),
	              path('aboutus/', include('aboutus.urls')),
	              path('signin/', include('signin.urls')),
	              path('logout/', LogoutView.as_view(next_page="home"), name='logout'),
	              path('profile/', include('accountProfile.urls')),
	              path('settings/', include('accountSettings.urls')),
	              path('conversion/', include('conversion.urls')),
	              path('creation/', include('creation.urls')),
	              path('documentation/', include('documentation.urls')),
	              path('help/', include('getHelp.urls')),
	              path('history/', include('history.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

getHelp/models.py
# Create your models here.
from django.db import models


class Contact(models.Model):
	name = models.CharField(max_length=255)
	email = models.EmailField()
	message = models.TextField()
	file = models.FileField(upload_to='fine_tuning/', blank=True)

	def __str__(self):
		return self.name

	class Help(models.TextChoices):
		GENERAL = 'general', 'General'
		FINE_TUNING = 'fine-tuning', 'Fine-tuning'

	helpType = models.CharField(
		max_length=15,
		choices=Help.choices,
		default=Help.GENERAL,
	)

getHelp/forms.py
from django import forms

from getHelp.models import Contact


class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		fields = ['name', 'email', 'message', 'file', 'helpType']

		widgets = {
			'name': forms.TextInput(attrs={
				'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-4 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500',
				'placeholder': 'name'
			}),
			'email': forms.EmailInput(attrs={
				'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-4 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500',
				'placeholder': 'guest@email.com'
			}),
			'message': forms.Textarea(attrs={
				'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-4 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 h-13',
				'placeholder': "I'm wondering about..."
			}),
			'helpType': forms.RadioSelect(attrs={
				'class': 'w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600'
			}),
			'file': forms.FileInput(attrs={})

		}

getHelp/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from accountProfile.models import UserProfile
from accountSettings.models import UserSettings
from getHelp.forms import ContactForm


def index(request):
	if request.user.is_authenticated:
		user_settings = UserSettings.objects.get(user=request.user)
		dark = user_settings.darkMode
		user_profile = UserProfile.objects.get(user=request.user)
	else:
		dark = False
		user_profile = None
	if request.method == 'POST':
		form = ContactForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			messages.success(request, 'Your message has been sent successfully!')
			return redirect('home')
		else:
			messages.error(request, 'There was something wrong with your input.')
	else:
		form = ContactForm()
	return render(request, 'getHelp/index.html', {'form': form, 'dark': dark,
	                                              'profile_picture': user_profile.profile_picture if user_profile and user_profile.profile_picture else None})

getHelp/templates/getHelp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="{% if dark %}dark{% endif %}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ShiftMate</title>
    <link href="{% static 'getHelp/css/output.css' %}" rel="stylesheet">
    <link rel="icon" href="{% get_media_prefix %}images/logo.png" type="image/x-icon">
    <script src="{% static 'getHelp/js/index.js' %}"></script>


</head>
<body class="bg-gray-100 dark:bg-gray-900 min-h-screen flex flex-col">
<header class="bg-blue-600 text-white py-4 dark:bg-blue-800">
</header>
{% include "home/menu.html" with dark=dark %}
<main class="flex-grow">
    <div class="container mx-auto mt-12 p-6 bg-white shadow-lg rounded-md mb-8 dark:bg-gray-800 dark:text-gray-200">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white text-center mb-4">
            Contact
            Us</h1>
        <p class="mb-4 lg:mb-16 font-light text-center text-gray-500 dark:text-white sm:text-xl">Have an issue? Do
            you want an additional OCR model for your specific problem? Contact us!</p>

        <form method="post" class="space-y-4 md:space-y-4">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div>
                <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Your
                    name</label>
                {{ form.name }}
            </div>
            <div>
                <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Your
                    email</label>
                {{ form.email }}
            </div>
            <div>
                <label for="message" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Your
                    message</label>
                {{ form.message }}
            </div>
            <div id="helpTypeField">
                <label for="helpType" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Type of inquiry
                </label>
                <div class="space-y-2">
                    {% for radio in form.helpType %}
                        <div class="flex items-center">
                            {{ radio.tag }}
                            <label for="{{ radio.id_for_label }}"
                                   class="ms-3 text-sm font-medium text-gray-900 dark:text-gray-300">
                                {{ radio.choice_label }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div id="file" class="hidden"
                 ondragover="event.preventDefault();"
                 ondrop="handleDrop(event)">
                <label for="id_file"
                       class="flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-gray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600">
                    <div class="flex flex-col items-center justify-center pt-5 pb-6">
                        <svg class="w-8 h-8 mb-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                             xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 16">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2"/>
                        </svg>
                        <p class="mb-2 text-sm text-gray-500 dark:text-gray-400"><span
                                class="font-semibold">Click to upload</span>
                            or drag and drop</p>
                        <p class="text-xs text-gray-500 dark:text-gray-400">SVG, PNG, JPG, or GIF (MAX. 800x400px)</p>
                    </div>
                    {{ form.file }}
                </label>
            </div>

            <div>
                <button type="submit"
                        name="action" value="help"
                        class="w-full bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700 transition dark:bg-blue-700 dark:hover:bg-blue-600">
                    Submit
                </button>
            </div>
        </form>
    </div>
</main>
<footer class="bg-gray-200 dark:bg-gray-800 text-gray-700 dark:text-gray-300 py-4">
    <div class="max-w-screen-xl mx-auto px-4 flex flex-col sm:flex-row justify-center items-center gap-4 text-sm text-center sm:text-left">

        <a href="https://www.termsfeed.com/live/47acb236-3302-486d-a621-de7eecae9fac"
           target="_blank"
           class="underline hover:text-blue-600 dark:hover:text-blue-400">
            Privacy Policy
        </a>
        <p>&copy; {{ now|date:"Y" }} ShiftMate. All rights reserved.</p>
        <a href="https://en.wikipedia.org/wiki/General_Data_Protection_Regulation"
           target="_blank"
           class="underline hover:text-blue-600 dark:hover:text-blue-400">
            GDPR
        </a>
    </div>
</footer>
</body>
</html>